// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServicioComunal.Data;

#nullable disable

namespace ServicioComunal.Migrations
{
    [DbContext(typeof(ServicioComunalDbContext))]
    [Migration("20250831210000_AgregarFechaEntregaDefinitiva")]
    partial class AgregarFechaEntregaDefinitiva
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Simplificado - este archivo se regenerará automáticamente
        }
    }
}
