// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServicioComunal.Data;

#nullable disable

namespace ServicioComunal.Migrations
{
    [DbContext(typeof(ServicioComunalDbContext))]
    partial class ServicioComunalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ServicioComunal.Models.Entrega", b =>
                {
                    b.Property<int>("Identificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Identificacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Identificacion"));

                    b.Property<string>("ArchivoRuta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ArchivoRuta");

                    b.Property<string>("DatosFormularioJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DatosFormularioJson");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Descripcion");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaEntrega");

                    b.Property<DateTime>("FechaLimite")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaLimite");

                    b.Property<DateTime?>("FechaRetroalimentacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaRetroalimentacion");

                    b.Property<int?>("FormularioIdentificacion")
                        .HasColumnType("int")
                        .HasColumnName("FORMULARIO_Identificacion");

                    b.Property<int>("GrupoNumero")
                        .HasColumnType("int")
                        .HasColumnName("GRUPO_Numero");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nombre");

                    b.Property<int?>("ProfesorIdentificacion")
                        .HasColumnType("int")
                        .HasColumnName("PROFESOR_Identificacion");

                    b.Property<string>("Retroalimentacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Retroalimentacion");

                    b.Property<int>("TipoAnexo")
                        .HasColumnType("int")
                        .HasColumnName("TipoAnexo");

                    b.HasKey("Identificacion");

                    b.HasIndex("FormularioIdentificacion");

                    b.HasIndex("GrupoNumero");

                    b.HasIndex("ProfesorIdentificacion");

                    b.ToTable("ENTREGA");
                });

            modelBuilder.Entity("ServicioComunal.Models.Estudiante", b =>
                {
                    b.Property<int>("Identificacion")
                        .HasColumnType("int")
                        .HasColumnName("Identificacion");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Apellidos");

                    b.Property<string>("Clase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Clase");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nombre");

                    b.HasKey("Identificacion");

                    b.ToTable("ESTUDIANTE");
                });

            modelBuilder.Entity("ServicioComunal.Models.Formulario", b =>
                {
                    b.Property<int>("Identificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Identificacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Identificacion"));

                    b.Property<string>("ArchivoRuta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ArchivoRuta");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Descripcion");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaIngreso");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nombre");

                    b.Property<int>("ProfesorIdentificacion")
                        .HasColumnType("int")
                        .HasColumnName("PROFESOR_Identificacion");

                    b.HasKey("Identificacion");

                    b.HasIndex("ProfesorIdentificacion");

                    b.ToTable("FORMULARIO");
                });

            modelBuilder.Entity("ServicioComunal.Models.Grupo", b =>
                {
                    b.Property<int>("Numero")
                        .HasColumnType("int")
                        .HasColumnName("Numero");

                    b.Property<int?>("LiderIdentificacion")
                        .HasColumnType("int")
                        .HasColumnName("LiderIdentificacion");

                    b.HasKey("Numero");

                    b.HasIndex("LiderIdentificacion");

                    b.ToTable("GRUPO");
                });

            modelBuilder.Entity("ServicioComunal.Models.GrupoEstudiante", b =>
                {
                    b.Property<int>("EstudianteIdentificacion")
                        .HasColumnType("int")
                        .HasColumnName("ESTUDIANTE_Identificacion")
                        .HasColumnOrder(0);

                    b.Property<int>("GrupoNumero")
                        .HasColumnType("int")
                        .HasColumnName("GRUPO_Numero")
                        .HasColumnOrder(1);

                    b.HasKey("EstudianteIdentificacion", "GrupoNumero");

                    b.HasIndex("GrupoNumero");

                    b.ToTable("GRUPO_ESTUDIANTE");
                });

            modelBuilder.Entity("ServicioComunal.Models.GrupoProfesor", b =>
                {
                    b.Property<int>("GrupoNumero")
                        .HasColumnType("int")
                        .HasColumnName("GRUPO_Numero")
                        .HasColumnOrder(0);

                    b.Property<int>("ProfesorIdentificacion")
                        .HasColumnType("int")
                        .HasColumnName("PROFESOR_Identificacion")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaAsignacion");

                    b.HasKey("GrupoNumero", "ProfesorIdentificacion");

                    b.HasIndex("ProfesorIdentificacion");

                    b.ToTable("GRUPO_PROFESOR");
                });

            modelBuilder.Entity("ServicioComunal.Models.Notificacion", b =>
                {
                    b.Property<int>("Identificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Identificacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Identificacion"));

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaHora");

                    b.Property<int>("GrupoNumero")
                        .HasColumnType("int")
                        .HasColumnName("GRUPO_Numero");

                    b.Property<bool>("Leido")
                        .HasColumnType("bit")
                        .HasColumnName("Leido");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Mensaje");

                    b.Property<int>("ProfesorIdentificacion")
                        .HasColumnType("int")
                        .HasColumnName("PROFESOR_Identificacion");

                    b.HasKey("Identificacion");

                    b.HasIndex("GrupoNumero");

                    b.HasIndex("ProfesorIdentificacion");

                    b.ToTable("NOTIFICACION");
                });

            modelBuilder.Entity("ServicioComunal.Models.Profesor", b =>
                {
                    b.Property<int>("Identificacion")
                        .HasColumnType("int")
                        .HasColumnName("Identificacion");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Apellidos");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nombre");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Rol");

                    b.HasKey("Identificacion");

                    b.ToTable("PROFESOR");
                });

            modelBuilder.Entity("ServicioComunal.Models.Solicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Estado");

                    b.Property<int>("EstudianteDestinatarioId")
                        .HasColumnType("int")
                        .HasColumnName("EstudianteDestinatarioId");

                    b.Property<int>("EstudianteRemitenteId")
                        .HasColumnType("int")
                        .HasColumnName("EstudianteRemitenteId");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<DateTime?>("FechaRespuesta")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaRespuesta");

                    b.Property<int?>("GrupoNumero")
                        .HasColumnType("int")
                        .HasColumnName("GrupoNumero");

                    b.Property<string>("Mensaje")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Mensaje");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Tipo");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteDestinatarioId");

                    b.HasIndex("EstudianteRemitenteId");

                    b.HasIndex("GrupoNumero");

                    b.ToTable("SOLICITUD");
                });

            modelBuilder.Entity("ServicioComunal.Models.Usuario", b =>
                {
                    b.Property<int>("Identificacion")
                        .HasColumnType("int")
                        .HasColumnName("Identificacion");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Contraseña");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Usuario");

                    b.Property<bool>("RequiereCambioContraseña")
                        .HasColumnType("bit")
                        .HasColumnName("RequiereCambioContraseña");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Rol");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime2")
                        .HasColumnName("UltimoAcceso");

                    b.HasKey("Identificacion");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("USUARIO");
                });

            modelBuilder.Entity("ServicioComunal.Models.Entrega", b =>
                {
                    b.HasOne("ServicioComunal.Models.Formulario", "Formulario")
                        .WithMany()
                        .HasForeignKey("FormularioIdentificacion");

                    b.HasOne("ServicioComunal.Models.Grupo", "Grupo")
                        .WithMany("Entregas")
                        .HasForeignKey("GrupoNumero")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ServicioComunal.Models.Profesor", "Profesor")
                        .WithMany("Entregas")
                        .HasForeignKey("ProfesorIdentificacion")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Formulario");

                    b.Navigation("Grupo");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("ServicioComunal.Models.Formulario", b =>
                {
                    b.HasOne("ServicioComunal.Models.Profesor", "Profesor")
                        .WithMany("Formularios")
                        .HasForeignKey("ProfesorIdentificacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("ServicioComunal.Models.Grupo", b =>
                {
                    b.HasOne("ServicioComunal.Models.Estudiante", "Lider")
                        .WithMany()
                        .HasForeignKey("LiderIdentificacion")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Lider");
                });

            modelBuilder.Entity("ServicioComunal.Models.GrupoEstudiante", b =>
                {
                    b.HasOne("ServicioComunal.Models.Estudiante", "Estudiante")
                        .WithMany("GruposEstudiantes")
                        .HasForeignKey("EstudianteIdentificacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ServicioComunal.Models.Grupo", "Grupo")
                        .WithMany("GruposEstudiantes")
                        .HasForeignKey("GrupoNumero")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("ServicioComunal.Models.GrupoProfesor", b =>
                {
                    b.HasOne("ServicioComunal.Models.Grupo", "Grupo")
                        .WithMany("GruposProfesores")
                        .HasForeignKey("GrupoNumero")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ServicioComunal.Models.Profesor", "Profesor")
                        .WithMany("GruposProfesores")
                        .HasForeignKey("ProfesorIdentificacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("ServicioComunal.Models.Notificacion", b =>
                {
                    b.HasOne("ServicioComunal.Models.Grupo", "Grupo")
                        .WithMany("Notificaciones")
                        .HasForeignKey("GrupoNumero")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ServicioComunal.Models.Profesor", "Profesor")
                        .WithMany("Notificaciones")
                        .HasForeignKey("ProfesorIdentificacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("ServicioComunal.Models.Solicitud", b =>
                {
                    b.HasOne("ServicioComunal.Models.Estudiante", "EstudianteDestinatario")
                        .WithMany()
                        .HasForeignKey("EstudianteDestinatarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ServicioComunal.Models.Estudiante", "EstudianteRemitente")
                        .WithMany()
                        .HasForeignKey("EstudianteRemitenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ServicioComunal.Models.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("GrupoNumero")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EstudianteDestinatario");

                    b.Navigation("EstudianteRemitente");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("ServicioComunal.Models.Estudiante", b =>
                {
                    b.Navigation("GruposEstudiantes");
                });

            modelBuilder.Entity("ServicioComunal.Models.Grupo", b =>
                {
                    b.Navigation("Entregas");

                    b.Navigation("GruposEstudiantes");

                    b.Navigation("GruposProfesores");

                    b.Navigation("Notificaciones");
                });

            modelBuilder.Entity("ServicioComunal.Models.Profesor", b =>
                {
                    b.Navigation("Entregas");

                    b.Navigation("Formularios");

                    b.Navigation("GruposProfesores");

                    b.Navigation("Notificaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
